<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Contentor Localization API</h4>
	</div>
    <fieldset id="Contentor">
		<p>
			<h3>Localization</h3>
			<label><input type="checkbox" name="translate" value="true"> Send on save</label>
		</p>
		<br>
		<p>
			<h3>Source store locale</h3>
			<?php
			// Get default locale from settings
			$defaultSource = Mage::getStoreConfig('contentor_options/contentor_source/contentor_source_input');
			$thisStoreId = Mage::app()->getRequest()->getParam('store');
			if(!$defaultSource) {
				$defaultSource = Mage::getStoreConfig('general/locale/code', $thisStoreId);
			}
			$this_sku  = Mage::registry('current_product')->getSku();
			// Get, and list all available locales
			$allLanguages = Mage::app()->getLocale()->getOptionLocales();
			?>
			<select name="source">
				<option value="">Choose source language</option>
				<?php 
					foreach($allLanguages as $lang) {
						print '<option value="' . $lang['value'] . '"';
						if($lang['value'] == $defaultSource) {
							print ' SELECTED';
						}
						print '>' . $lang['label'] . '</option>';
					}
				?>
			</select>
			<br>
			
		</p>
		<br>
		<p>
			<h3>Target store view(s)</h3>
			<?php
			// Get stores if sent before
			
			// Else get default stores
			$defaultstores = explode(',',Mage::getStoreConfig('contentor_options/contentor_targets/contentor_targets_input'));
			
			$storesStructure = Mage::getSingleton('adminhtml/system_store')->getStoresStructure();
			foreach($storesStructure as $website) {
				print "<b>";
				print $website['label'];
				print "</b><br>";
				foreach($website['children'] as $store) {
					print "&nbsp;&nbsp;&nbsp;<b><i>";
					print $store['label'];
					print "</i></b><br>";
					foreach($store['children'] as $storeview) {
						$id = $storeview['value'];
						$name = $storeview['label'];
						$locale = str_replace('_', '-', Mage::getStoreConfig('general/locale/code', $id));
						if(in_array($id, $defaultstores)) {
							$checked = 'checked';
						} else {
							$checked = '';
						}
						print '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label><input type="checkbox" name="targets[]" value="' . $id . '" id="store_' . $id . '" ' . $checked . '> ' . $name . ' (' . $locale .')</label><br>';
					}
				}
			}
			?>
		</p>
		<br>
		<p>
			<div class="entry-edit">
				<div class="section-config">
					<div class="entry-edit-head collapseable">
						<a href="#" id="data_to_send-head" onclick="Fieldset.toggleCollapse('data_to_send', '<?php print Mage::helper('core/url')->getCurrentUrl(); ?>'); return false;">Data to send</a>
					</div>
					<input id="data_to_send-state" name="config_state_data_to_send" type="hidden" value="0">
					<fieldset class="config collapseable" id="data_to_send">
							<!--  Get my fields and print them nicely! -->
							<?php
							require_once(Mage::getModuleDir('', 'Contentor_LocalizationApi') . '/lib/api/ContentorAPI.php');
							$fields = ContentorAPI::getFieldData(Mage::registry('current_product'), 'product');
							foreach($fields as $field) {
								if($field['id'] != 'auto_sku') {
									print '<p><b>' . $field['name'] . '</b> ';
									print '(<i>' . $field['type'] . '</i>)<br>';
									print htmlspecialchars($field['value']) . '</p>';
								}
							}
							?>
					</fieldset>
					<script type="text/javascript">
						//<![CDATA[
	        				Fieldset.applyCollapse('data_to_send');
	        			//]]>
            		</script>
				</div>
			</div>
		</p>
		<p>
		<?php 
		$contextName = Mage::getStoreConfig('contentor_context/contentor_context_data/contentor_context_products_contextname');
		$contextValue = Mage::getStoreConfig('contentor_context/contentor_context_data/contentor_context_products_context');
		if(!empty($contextValue)) {
			$collapsed = 1;
		} else {
			$collapsed = 0;
		}
		?>
			<div class="entry-edit">
				<div class="section-config">
					<div class="entry-edit-head collapseable">
						<a href="#" id="context-head" onclick="Fieldset.toggleCollapse('context', '<?php print Mage::helper('core/url')->getCurrentUrl(); ?>'); return false;">Add extra content context</a>
					</div>
					<input id="context-state" name="config_state_context" type="hidden" value="<?php print $collapsed; ?>">
					<fieldset class="config collapseable" id="context">
						<b>Context name</b><br>
						<input type="text" name="contextname" value="<?php print $contextName; ?>"><br><br>
						<b>Context</b><br>
						<textarea name="context" style="width:100%" rows=7 id="context-content"><?php 
						print $contextValue;
						?></textarea><br>
						<i>Context from this field will be visible for the writers.</i>
					</fieldset>
					<script type="text/javascript">
						//<![CDATA[
	        				Fieldset.applyCollapse('context');
	        			//]]>
            		</script>
				</div>
			</div>
		</p>
		<br>
		<p>
			<h3>Request status</h3>
			<?php 
			// Get and print log for this product
			$resource = Mage::getSingleton('core/resource');
			$readConnection = $resource->getConnection('core_read');
			$statustable = Mage::getConfig()->getTablePrefix()."contentor_status";
			$producttable = Mage::getConfig()->getTablePrefix()."contentor_products";
			$query = "SELECT `" . $producttable . "`.`contentor_id`, `" . $producttable . "`.`target_store`, `" . $producttable . "`.`sent_time`, `" . $producttable . "`.`completed_time`, `" . $producttable . "`.`canceled_time`, `" . $statustable . "`.`status_time`, `" . $statustable . "`.`status`, `" . $producttable . "`.`state`, `" . $producttable . "`.`type` FROM `" . $producttable . "` LEFT JOIN `" . $statustable . "` ON `" . $producttable . "`.`contentor_id`= `" . $statustable . "`.`contentor_id` WHERE `" . $producttable . "`.`sku` = :this_sku ORDER BY `" . $producttable . "`.`contentor_id` DESC, `" . $statustable . "`.`status_time`";
			$binds = array('this_sku'=>$this_sku);
			$messages = $readConnection->fetchAll($query, $binds);
			$lastId = '';
			if(count($messages)) {
				// I have content
				print '<ul class="messages">';
				foreach($messages as $message) {
					if($message['contentor_id'] != $lastId) {

						// If not for the first time ever print the end of prev.
						if($lastId) {
							print '</ul>';
							print '</li>';
						}
						
						// New request, print header and button if needed
						if($message['state'] == 'canceled') {
							// Product canceled
							print '<li class="error-msg">';
							print '<h4>Canceled</h4>';
						} else if($message['state'] == 'confirmed') {
							print '<li class="notice-msg">';
							print '<h4 style="float:left">Confirmed</h4>';
							print '<div class="form-buttons"><button onClick="fetchSingle(\'' . $message['contentor_id'] . '\',\'product\'); return false;">Look for updates</button></div>';
							print '<div style="clear:both"></div>';
							
						} else if($message['state'] == 'completed' || $message['completed_time'] != null) {
							// Product completed
							print '<li class="success-msg">';
							print '<h4>Completed ' . $message['completed_time'] . '</h4>';
						} else {
							print '<li class="notice-msg">';
							print '<h4 style="float:left">Sent ' . $message['sent_time'] . '</h4>';
							print '<div class="form-buttons"><button onClick="fetchSingle(\'' . $message['contentor_id'] . '\',\'product\'); return false;">Look for updates</button></div>';
							print '<div style="clear:both"></div>';
							
						}
						
						print '<p>Target store: ' . Mage::getModel('core/store')->load($message['target_store'])->getName() . '<br>';
						if(!empty($message['type'])) {
							$type = $message['type'];
						} else {
							$type = 'standard';
						}
						print 'Request type: ' . $type . '</p>';

						// Print the status rows
						$lastId = $message['contentor_id'];
						print '<hr>';
						print '<p><h5>Log messages</h5>';
						print '<ul>';
					}
					
					// This happens every iteration
					print '<li><i>' . $message['status_time'] . '</i> - ' . $message['status'] . '</li>';
					
				}
				print '</ul></p>';
				print '</li>';
				print '</ul>';
			} else {
				print "<i>(No events to show)</i>";
			}
			?>
		</p>
	</fieldset>
</div>
<script type="text/javascript">
//<![CDATA[
	function fetchSingle(id, type) {
		new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/Contentor/fetchSingle') ?>', {
			method:     'GET',
			parameters: { id, type },
			onSuccess: function(transport) {
				if(transport.responseText) {
				// If response was that changes was found, reload page if user wants to!
					if(confirm('Changes was found, reload page?')) {
							location.reload();
					} else {
						return false;
					}
				} else {
					alert('No state changes was found');
				}
			}
		});
	}
//]]>
</script>