<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Contentor Localization API</h4>
	</div>
    <fieldset id="Contentor">
		<p>
			<h3>Localization</h3>
			<label><input type="checkbox" name="translate" value="true"> Send on save</label>
		</p>
		<p>
			<h3>Source store locale</h3>
			<?php
			// Get default locale from settings
			$defaultSource = Mage::getStoreConfig('contentor_options/contentor_source/contentor_source_input');
			$thisStoreId = Mage::app()->getRequest()->getParam('store');
			if(!$defaultSource) {
				$defaultSource = Mage::getStoreConfig('general/locale/code', $thisStoreId);
			}
			$this_sku  = Mage::registry('current_product')->getSku();
			// Get, and list all available locales
			$allLanguages = Mage::app()->getLocale()->getOptionLocales();
			?>
			<select name="source">
				<option value="">Choose source language</option>
				<?php 
					foreach($allLanguages as $lang) {
						print '<option value="' . $lang['value'] . '"';
						if($lang['value'] == $defaultSource) {
							print ' SELECTED';
						}
						print '>' . $lang['label'] . '</option>';
					}
				?>
			</select>
			<br>
			
		</p>
		
		<p>
			<h3>Target store view(s)</h3>
			<?php
			// Get stores if sent before
			
			// Else get default stores
			$defaultstores = explode(',',Mage::getStoreConfig('contentor_options/contentor_targets/contentor_targets_input'));
			
			$storesStructure = Mage::getSingleton('adminhtml/system_store')->getStoresStructure();
			foreach($storesStructure as $website) {
				print "<b>";
				print $website['label'];
				print "</b><br>";
				foreach($website['children'] as $store) {
					print "&nbsp;&nbsp;&nbsp;<b><i>";
					print $store['label'];
					print "</i></b><br>";
					foreach($store['children'] as $storeview) {
						$id = $storeview['value'];
						$name = $storeview['label'];
						$locale = str_replace('_', '-', Mage::getStoreConfig('general/locale/code', $id));
						if(in_array($id, $defaultstores)) {
							$checked = 'checked';
						} else {
							$checked = '';
						}
						print '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label><input type="checkbox" name="targets[]" value="' . $id . '" id="store_' . $id . '" ' . $checked . '> ' . $name . ' (' . $locale .')</label><br>';
					}
				}
			}
			?>
		</p>
		
		<p>
		<h3>Localization log</h3>
			<ul class="messages">
				<?php 
				// Get and print log for this product
				$resource = Mage::getSingleton('core/resource');
				$readConnection = $resource->getConnection('core_read');
				$statustable = Mage::getConfig()->getTablePrefix()."contentor_status";
				$producttable = Mage::getConfig()->getTablePrefix()."contentor_products";
				$query = "SELECT `" . $statustable . "`.`status_time`, `" . $statustable . "`.`status` FROM `" . $producttable . "` LEFT JOIN `" . $statustable . "` ON `" . $producttable . "`.`contentor_id`= `" . $statustable . "`.`contentor_id` WHERE `" . $producttable . "`.`sku` = :this_sku ORDER BY `" . $statustable . "`.`status_time`";
				$binds = array('this_sku'=>$this_sku);
				$messages = $readConnection->fetchAll($query, $binds);
				foreach($messages as $message) {
					if(substr($message['status'], 0, 8) == 'Received') {
						print '<li class="success-msg">';
					} else {
						print '<li class="notice-msg">';
					}
						print '<ul>';
							print '<li><i>' . $message['status_time'] . '</i></li>';
							print '<li>' . $message['status'] . '</li>';
						print '</ul>';
					print '</li>';
				}
				?>
			</ul>
		</p>
	</fieldset>
</div>