<script type="text/javascript">
    //<![CDATA[
    function check() {
        var token = document.getElementById('contentor_options_contentor_token_contentor_token_input').value;
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            parameters: { token },
            onSuccess: function(transport) {
	            if (transport.responseText) {
	                alert('Token verified as: ' + transport.responseText);
	            } else {
	            	alert('Token invalid!');
	            }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml(); ?>